apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  # 类文件键
  front-nginx.conf: |-
    server {
      listen       8080;
      server_name  localhost;

      # 开启gzip压缩
      #      gzip on;
      #      gzip_disable "msie6";
      #      gzip_vary on;
      #      gzip_proxied any;
      #      gzip_comp_level 6;
      #      gzip_buffers 16 8k;
      #      gzip_http_version 1.1;
      #      gzip_types text/plain application/css text/css application/xml text/javascript application/javascript application/x-javascript;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
