apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-front-deployment
spec:
  selector:
    matchLabels:
      app: blog-front
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-front
    spec:
      nodeName: ecs-2rsvn
      containers:
        - name: blog-api
          image: jornahlee/blog-front:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: "/etc/nginx/conf.d/"
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
