apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-front-deployment
spec:
  selector:
    matchLabels:
      app: blog-front
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-front
    spec:
      nodeName: centos-free
      containers:
        - name: blog-api
          image: docker-registry.499801.xyz/blog-front:latest
          ports:
            - containerPort: 80
