apiVersion: v1
kind: Service
metadata:
  name: blog-front-svc
spec:
  selector:
    app: blog-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
