apiVersion: v1
kind: Service
metadata:
  name: blog-api-svc
spec:
  selector:
    app: blog-api
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30001
  type: NodePort
